# -*- coding: utf-8 -*-
"""copilot_api.py
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/13Ny8ORbGlrXGG-xyS5QU2QjDfGR09G2s
"""
# models/copilot_api.py
import os
import openai
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

class CopilotAPI:
    def __init__(self):
        """Initialize the Copilot API integration"""
        # You'll need to create a .env file with your GitHub Copilot API key
        openai.api_key = os.getenv("GITHUB_COPILOT_API_KEY")
        # Set the API base URL for GitHub Copilot (this may vary)
        openai.api_base = os.getenv("GITHUB_COPILOT_API_BASE", "https://api.githubcopilot.com/v1")
        # Check if API key is available
        if not openai.api_key:
            print("Warning: GitHub Copilot API key not found. Please set GITHUB_COPILOT_API_KEY in .env file")
            
    def generate_code(self, prompt, max_tokens=1024, temperature=0.2):
        """Generate code using GitHub Copilot API"""
        try:
            response = openai.Completion.create(
                model="copilot-codex",  # This model name may need to be updated
                prompt=prompt,
                max_tokens=max_tokens,
                temperature=temperature,
                top_p=1.0,
                frequency_penalty=0.0,
                presence_penalty=0.0
            )
            if response and response.choices and len(response.choices) > 0:
                return response.choices[0].text
            return ""
        except Exception as e:
            print(f"Error generating code with Copilot API: {e}")
            return ""

# Alternative implementation using GitHub Copilot CLI
# This is a fallback if direct API access isn't available
class CopilotCLI:
    def __init__(self, temp_file_dir="temp"):
        """Initialize the Copilot CLI integration"""
        self.temp_dir = temp_file_dir
        os.makedirs(self.temp_dir, exist_ok=True)
        
    def generate_code(self, prompt, language="python"):
        """
        Generate code using GitHub Copilot CLI
        This requires GitHub Copilot CLI to be installed:
        npm install -g @githubnext/github-copilot-cli
        """
        import subprocess
        import tempfile
        
        # Create temporary file with the prompt
        file_ext = ".py" if language == "python" else ".txt"
        temp_file = os.path.join(self.temp_dir, f"prompt{file_ext}")
        with open(temp_file, "w") as f:
            f.write(prompt)
        
        try:
            # Run GitHub Copilot CLI command
            # This assumes 'github-copilot-cli' is in your PATH
            result = subprocess.run(
                ["github-copilot-cli", "suggest", "--file", temp_file],
                capture_output=True,
                text=True,
                timeout=30
            )
            if result.returncode == 0 and result.stdout:
                return result.stdout
            else:
                print(f"Error: {result.stderr}")
                return ""
        except Exception as e:
            print(f"Error using Copilot CLI: {e}")
            return ""
        finally:
            # Clean up temporary file
            if os.path.exists(temp_file):
                os.remove(temp_file)